name: Build docs
description: Build mkdocs
inputs:
  name:
    required: false
    description: "Name"

outputs:
  random:
    description: "Random number output"
    value: ${{ steps.step1.outputs.random }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies for mkdocs
      run: | 
        pip install -r documentation/mkdocs-requirements.txt
      shell: bash

    - name: Build documentation
      working-directory: documentation
      run: |
        # outputs to "site" directory
        mkdocs build -f mkdocs.yml
      shell: bash
